---
title: Nuit du Code Citoyen
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: pages/participer
    type: pages
  values:
    layout: default
    author: Mr. Hyde
email: jarrive@nuitcodecitoyen.org
description: La Nuit du Code Citoyen est un hackathon d'innovation du 15 au 17 mai
  2020 associant défis technologiques, considérations éthiques et finalités sociales
  en simultané dans plusieurs villes de pays francophones. L’événement est suivi d’un
  programme d’accompagnement sur la durée et d'actions de médiation
twitter: codecitoyen
github: codecitoyen
facebook: lesbricodeurs
linkedin: bricodeur
url: https://nuitcodecitoyen.org
baseurl: ''
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
encoding: utf-8
locale: fr
exclude:
- gabarit
- lib
- config.rb
- Capfile
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- vendor
paginate: 6
paginate_path: blog/page:num
